exports.jobs = [
  'VP Marketing',
  'Marketing Associate',
  'Brand Manager',
  'Technician',
  'Software Engineer',
  'Marketing Assistant',
  'Electrician',
  'Marketing Manager',
  'SoftwareDeveloper',
  'Marketing Coordinator',
  'Project Manager',
  'Bank Manager',
  'Accountant',
  'Secretary',
  'Speaker',
  'Civil Engineer',
  'Doctor',
  'Teacher',
  'Professor',
  'Business Man',
  'Soprts Man',
  'Teacher',
  'Worker',
  'CFO',
  'CEO',
  'CTO',
  'CMO',
]
